/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF, Float, Text } from "@react-three/drei";

export function Model({ showFrance = null, ...props }) {
  const { nodes, materials } = useGLTF("/terre_pins_test.glb");
  const handleclick = (event) => {
    event.stopPropagation();
    console.log("Test");
  };
  const pinPosition = nodes.Cube007.position;

  return (
    <group {...props} dispose={null} rotation={[0.1, 2.1, 0.1]}>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.earth.geometry}
        material={materials["Default OBJ"]}
        scale={0.005}
      ></mesh>
      <Float
        speed={1} // vitesse du flottement
        rotationIntensity={2} // intensité de la rotation
        floatIntensity={2} // intensité du flottement
      >
        <group
          onClick={handleclick}
          position={[1.664, 2.266, -1.337]}
          rotation={[-0.72, -0.175, 2.702]}
          scale={[0.039, 0.071, 0.039]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_2.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_3.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_4.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_5.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_6.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_7.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_8.geometry}
            material={materials["Material.019"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_9.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_10.geometry}
            material={materials["Material.021"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_11.geometry}
            material={materials["Material.022"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_12.geometry}
            material={materials["Material.023"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_13.geometry}
            material={materials["Material.024"]}
          />
        </group>
      </Float>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pin1.geometry}
        material={materials["Material.009"]}
        scale={0.005}
      />
      <group scale={0.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      {showFrance && (
        <group scale={0.005}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
      )}
      <group scale={0.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials["Material.006"]}
        />
      </group> */}
      <group
        scale={0.005}
        onClick={() => {
          alert("Test");
        }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials["Material.008"]}
        />

        {/* Place le texte légèrement au-dessus du pin */}
        <Text
          position={pinPosition} // Position ajustée au-dessus du pin (Y augmenté)
          scale={[50, 50, 50]}
          color="black"
          anchorX="center"
          anchorY="middle"
        >
          HELLO WORLD
        </Text>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.010"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/terre_pins_test.glb");

export default Model;
